import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import livereload from 'rollup-plugin-livereload';
import terser from '@rollup/plugin-terser';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const production = !process.env.ROLLUP_WATCH;
const cssVersionBanner = '/* Generated from frontend/src/styles. Do not edit this file directly. */';
const styleSourceDir = path.join('src', 'styles');
const styleOutputPath = path.join('public', 'app.css');
const styleEntries = [
  'tokens.css',
  'base.css',
  'layout.css',
  'components.css',
  'pages.css',
];

// One entry per real HTML page that loads a compiled bundle from public/build/.
// Keep this list explicit so empty legacy files do not become public build output.
const pageEntries = [
  'dashboard',
  'login',
  'register',
  'profile',
  'edit-profile',
  'plan-trip',
  'route-details',
  'saved-routes',
];

function buildStyles() {
  const css = [cssVersionBanner]
    .concat(styleEntries.map((entry) => readFileSync(path.join(styleSourceDir, entry), 'utf8').trim()))
    .join('\n\n')
    .trim();

  mkdirSync(path.dirname(styleOutputPath), { recursive: true });
  writeFileSync(styleOutputPath, `${css}\n`);
}

function createPlugins() {
  return [
    resolve({ browser: true }),
    commonjs(),
    !production && livereload('public'),
    production && terser(),
  ].filter(Boolean);
}

function createPageBundle(entryName) {
  const safeName = entryName.replace(/[^A-Za-z0-9_$]/g, '_');

  return {
    input: `src/${entryName}.js`,
    output: {
      file: `public/build/${entryName}.js`,
      format: 'iife',
      name: `${safeName}Page`,
      sourcemap: !production,
    },
    plugins: createPlugins(),
    watch: {
      clearScreen: false,
    },
  };
}

buildStyles();

export default pageEntries.map(createPageBundle);
